import type { FairePartPage, Condolence } from "./types";

export const demoFaireParts: FairePartPage[] = [
  {
    id: "papa-jean-tchinda",
    slug: "papa-jean-tchinda",
    eventType: "funerailles",
    titre: "Faire-part de deces et de funerailles",
    sousTitre:
      "La grande famille Tchinda, les enfants, petits-enfants, freres, soeurs, neveux et nieces, les notables du groupement Foto, ont la profonde douleur de vous annoncer le deces de leur pere, grand-pere, frere, oncle et notable",
    versetBiblique: "Je suis la resurrection et la vie. Celui qui croit en moi vivra, meme s'il meurt. - Jean 11:25",
    symboleReligieux: "croix",
    personnes: [
      {
        nom: "Tchinda",
        prenoms: "Jean Pierre",
        titreHonorifique: "Feu Papa",
        surnom: "Le Sage de Foto",
        dateNaissance: "12 mars 1945",
        dateDeces: "8 avril 2026",
        lieuNaissance: "Foto, Dschang",
        lieuDeces: "Hopital de district de Dschang",
        ageAuDeces: 81,
        causeDecesMention: "des suites d'une courte maladie",
        photoPortrait: "/images/portrait-grandpere.jpg",
        profession: "Enseignant a la retraite",
        gradeOuFonction: "Ancien Directeur du Lycee de Dschang",
        titreTradi: "Notable du groupement Foto - 7 cranes",
        decorations: ["Chevalier de l'Ordre de la Valeur"],
        villageOrigine: "Foto",
        chefferie: "Groupement Foto",
      },
    ],
    famille: [
      {
        categorie: "epouse",
        membres: [
          { nom: "Mme Tchinda nee Kengne Marie Claire" },
        ],
      },
      {
        categorie: "enfants",
        membres: [
          { nom: "Tchinda Paul", mention: "(Aine)", villeResidence: "Douala, Cameroun" },
          { nom: "Tchinda Sylvie", conjoint: "epse Mboua", villeResidence: "Paris, France" },
          { nom: "Tchinda Emmanuel", mention: "et famille", villeResidence: "Montreal, Canada" },
          { nom: "Tchinda Rose", conjoint: "epse Kamga", villeResidence: "Yaounde, Cameroun" },
          { nom: "Tchinda Franck", villeResidence: "Bruxelles, Belgique" },
          { nom: "Tchinda Estelle", conjoint: "epse Njoya", villeResidence: "Dschang, Cameroun" },
          { nom: "Tchinda Alain", mention: "et epouse", villeResidence: "Berlin, Allemagne" },
          { nom: "Tchinda Isabelle", conjoint: "epse Tamo", villeResidence: "Douala, Cameroun" },
        ],
      },
      {
        categorie: "petits-enfants",
        membres: [{ nom: "22 petits-enfants" }],
      },
      {
        categorie: "freres-soeurs",
        membres: [
          { nom: "Tchinda Joseph", villeResidence: "Dschang" },
          { nom: "Tchinda Marthe", conjoint: "epse Djomo", villeResidence: "Bafoussam" },
          { nom: "Tchinda Samuel", estDecede: true },
          { nom: "Tchinda Bernadette", villeResidence: "Yaounde" },
        ],
      },
      {
        categorie: "belle-famille",
        membres: [
          { nom: "Famille Kengne (belle-famille)" },
          { nom: "Famille Mboua" },
          { nom: "Famille Kamga" },
          { nom: "Famille Tamo" },
          { nom: "Famille Njoya" },
        ],
      },
      {
        categorie: "notable",
        membres: [
          { nom: "Sa Majeste le Chef superieur de Foto" },
          { nom: "Les notables du groupement Foto" },
        ],
      },
      {
        categorie: "associations",
        membres: [
          { nom: "Association des ressortissants de Foto a Douala" },
          { nom: "Association des enseignants retraites de Dschang" },
          { nom: "Tontine familiale Tchinda" },
        ],
      },
      {
        categorie: "communaute-religieuse",
        membres: [
          { nom: "Communaute chretienne de la paroisse Saint-Joseph de Dschang" },
        ],
      },
    ],
    programme: [
      {
        id: "jour-1",
        jour: "Jeudi 14 avril 2026",
        evenements: [
          {
            heure: "15h00",
            titre: "Restitution de la depouille",
            lieu: "Hopital de district de Dschang",
            description: "Transport de la depouille vers le domicile familial.",
            typeEvenement: "autre",
          },
          {
            heure: "18h00",
            titre: "Arrivee de la depouille au domicile",
            lieu: "Domicile familial, quartier Foto",
            description: "Accueil de la depouille par la famille et les notables. Exposition.",
            typeEvenement: "traditionnel",
          },
          {
            heure: "20h00",
            titre: "Veillee funebre",
            lieu: "Domicile familial, quartier Foto",
            description: "Veillee animee par la chorale de la paroisse Saint-Joseph. Temoignages, prieres et chants. Repas offert aux invites.",
            typeEvenement: "veillee",
            codeVestimentaire: "Tenue sombre ou pagne de deuil",
          },
        ],
      },
      {
        id: "jour-2",
        jour: "Vendredi 15 avril 2026",
        evenements: [
          {
            heure: "06h00",
            titre: "Toilette mortuaire et mise en biere",
            lieu: "Domicile familial",
            typeEvenement: "autre",
          },
          {
            heure: "08h00",
            titre: "Levee de corps",
            lieu: "Domicile familial, quartier Foto",
            description: "En presence de la famille, des notables et des proches.",
            typeEvenement: "autre",
            codeVestimentaire: "Pagne de deuil du groupement Foto (disponible chez Mme Kengne au 699 XX XX XX)",
          },
          {
            heure: "09h00",
            titre: "Messe de requiem",
            lieu: "Eglise catholique Saint-Joseph de Dschang",
            description: "Celebree par l'Abbe Pierre Ngounou. Oraisons funebres, temoignages, chorale paroissiale.",
            typeEvenement: "religieux",
            celebrant: "Abbe Pierre Ngounou",
            adresse: "Centre-ville de Dschang",
          },
          {
            heure: "11h30",
            titre: "Cortege funebre",
            lieu: "De l'eglise vers le cimetiere de Foto",
            typeEvenement: "cortege",
          },
          {
            heure: "12h00",
            titre: "Inhumation",
            lieu: "Concession familiale, Foto",
            description: "Mise en terre selon les rites traditionnels et chretiens. Danse des notables.",
            typeEvenement: "traditionnel",
          },
          {
            heure: "13h30",
            titre: "Grand repas de reception",
            lieu: "Esplanade du domicile familial",
            description: "Repas de reception pour tous les invites. 800 places assises. Menu traditionnel.",
            typeEvenement: "reception",
          },
        ],
      },
    ],
    fairePartPhotos: [
      { id: "fp-1", url: "/images/famille-africaine.jpg", caption: "En famille au domicile", type: "photo" as const, tags: ["famille" as const], isDownloadable: false, isCover: false, isRecap: false, order: 1 },
      { id: "fp-2", url: "/images/portrait-grandpere.jpg", caption: "Papa Jean dans sa jeunesse", type: "photo" as const, tags: ["portrait" as const], isDownloadable: false, isCover: false, isRecap: false, order: 2 },
      { id: "fp-3", url: "/images/mains-famille.jpg", caption: "Trois generations unies", type: "photo" as const, tags: ["famille" as const], isDownloadable: false, isCover: false, isRecap: false, order: 3 },
    ],
    photos: [
      { id: "1", url: "/images/event-2.jpg", caption: "Les tables de la reception dressees avec soin", type: "photo" as const, tags: ["reception" as const], programmeEventId: "jour-2-13h30", addedBy: "ETS Mme Jesus", isDownloadable: true, isCover: false, isRecap: false, order: 1 },
      { id: "2", url: "/images/event-4.jpg", caption: "Vue panoramique de la salle decoree", type: "photo" as const, tags: ["decoration" as const], programmeEventId: "jour-2-13h30", addedBy: "ETS Mme Jesus", isDownloadable: true, isCover: false, isRecap: false, order: 2 },
      { id: "3", url: "/images/ceremony-1.jpg", caption: "Preparation de la salle de reception", type: "photo" as const, tags: ["decoration" as const], programmeEventId: "jour-1-18h00", addedBy: "ETS Mme Jesus", isDownloadable: true, isCover: false, isRecap: false, order: 3 },
      { id: "4", url: "/images/ceremony-3.jpg", caption: "La salle prete a accueillir les invites", type: "photo" as const, tags: ["reception" as const], programmeEventId: "jour-2-13h30", addedBy: "Tchinda Sylvie", isDownloadable: true, isCover: false, isRecap: false, order: 4 },
      { id: "5", url: "/images/event-5.jpg", caption: "Detail des couverts et serviettes", type: "photo" as const, tags: ["decoration" as const], addedBy: "Pierre Kamga", isDownloadable: true, isCover: false, isRecap: false, order: 5 },
      { id: "6", url: "/images/ceremony-2.jpg", caption: "L'equipe en plein amenagement", type: "photo" as const, tags: ["decoration" as const], addedBy: "ETS Mme Jesus", isDownloadable: true, isCover: false, isRecap: false, order: 6 },
      { id: "7", url: "/images/event-6.jpg", caption: "Les nappes et la vaisselle doree", type: "photo" as const, tags: ["reception" as const], programmeEventId: "jour-2-13h30", addedBy: "Tchinda Rose", isDownloadable: true, isCover: false, isRecap: false, order: 7 },
      { id: "8", url: "/images/ceremony-4.jpg", caption: "Vue generale sous la tente", type: "photo" as const, tags: ["reception" as const], addedBy: "Famille Mboua", isDownloadable: true, isCover: false, isRecap: false, order: 8 },
      { id: "9", url: "/images/famille-africaine.jpg", caption: "La famille au domicile", type: "photo" as const, tags: ["famille" as const], addedBy: "Sarah Tchinda", isDownloadable: true, isCover: false, isRecap: false, order: 9 },
    ],
    epitaphe: "Un homme de coeur, un pilier de sa famille, un exemple pour sa communaute. Que la terre de nos ancetres lui soit legere.",
    biographie: "Ne a Foto (Dschang) le 12 mars 1945, Jean Pierre Tchinda a consacre sa vie a l'education et a sa communaute. Diplome de l'Ecole Normale Superieure, il a enseigne pendant plus de 35 ans dans les lycees et colleges de l'Ouest Cameroun.\n\nEpoux devoue de Marie Claire Kengne depuis 1970, pere de 8 enfants et grand-pere de 22 petits-enfants, il etait un pilier incontestable de sa famille. Notable du groupement Foto avec 7 cranes, il a oeuvre sans relache pour le developpement de sa communaute.\n\nSon integrite, sa rigueur et sa generosite etaient connues de tous. Il s'est eteint paisiblement le 8 avril 2026 a l'hopital de district de Dschang, entoure de l'amour des siens.",
    remerciements: "La famille Tchinda remercie sincerement le personnel medical de l'hopital de district de Dschang, la communaute chretienne de la paroisse Saint-Joseph, Sa Majeste le Chef superieur de Foto et tous les notables, ainsi que toutes les personnes qui, de pres ou de loin, ont apporte leur soutien moral, materiel et financier en ces moments difficiles.",
    contactsFamille: [
      { nom: "Tchinda Paul (Aine)", telephone: "+237 699 12 34 56", ville: "Douala", role: "President du comite" },
      { nom: "Tchinda Emmanuel", telephone: "+1 514 555 0123", ville: "Montreal", role: "Coordination diaspora" },
      { nom: "Tchinda Rose epse Kamga", telephone: "+237 677 88 99 00", ville: "Yaounde" },
    ],
    contactOrganisateur: "+1 418 490 1849",
    adresseReception: "Domicile familial, quartier Foto, Dschang",
    codeVestimentaire: "Pagne de deuil du groupement Foto ou tenue sombre",
    pagneInfo: "Pagne disponible chez Mme Kengne Marie Claire au +237 699 XX XX XX (5 000 FCFA le metre)",
    infoHebergement: "Hebergement possible au domicile familial et chez les voisins. Hotel Meumi Palace (Dschang centre) : +237 233 45 XX XX",
    infoTransport: "Navettes organisees depuis Douala (depart Bonaberi 05h00) et Yaounde (depart Mvan 04h00). Contact : Tchinda Paul au +237 699 12 34 56",
    celebrant: "Abbe Pierre Ngounou",
    comiteOrganisation: [
      "Tchinda Paul (President)",
      "Kengne Martin (Tresorier)",
      "Mme Djomo Marthe (Restauration)",
      "Fonkou Jean (Logistique)",
    ],
    contributions: {
      message: "La famille Tchinda vous serait reconnaissante pour toute contribution destinee a accompagner dignement Papa Jean dans sa derniere demeure.",
      orangeMoney: "699 12 34 56 (Tchinda Paul)",
      mtnMomo: "677 88 99 00 (Tchinda Rose)",
      rib: "BICEC - Compte N° 10001 00025 12345678901 42",
      interac: "tchinda.emmanuel@email.com",
      nomBeneficiaire: "Comite d'organisation des obseques Tchinda",
    },
    isPrivate: false,
    isPublished: true,
    isPending: false,
    allowCondolences: true,
    allowPhotoDownload: true,
    familleName: "Famille Tchinda",
    ville: "Dschang",
    region: "Ouest",
    coverImage: "/images/event-1.jpg",
    createdAt: "2026-04-10",
    updatedAt: "2026-04-10",
    fairePartDesign: {
      primaryColor: "#1F2E1F",
      accentColor: "#B8935A",
      backgroundColor: "#F5F1E8",
      borderStyle: "bamileke",
      template: "funerailles",
    },
  },
  {
    id: "mariage-kamga-fonkou",
    slug: "mariage-kamga-fonkou",
    eventType: "mariage-traditionnel",
    titre: "Invitation au mariage traditionnel",
    sousTitre:
      "Les familles Kamga et Fonkou ont le plaisir et l'immense joie de vous inviter au mariage traditionnel (dot) de leurs enfants",
    versetBiblique: "Ce que Dieu a uni, que l'homme ne le separe pas. - Marc 10:9",
    symboleReligieux: "croix",
    personnes: [
      {
        nom: "Kamga",
        prenoms: "Armel Thierry",
        photoPortrait: "/images/portrait-marie.jpg",
        profession: "Ingenieur informatique",
        villageOrigine: "Bafou",
        lieuResidence: "Douala",
      },
      {
        nom: "Fonkou",
        prenoms: "Grace Danielle",
        photoPortrait: "/images/portrait-mariee.jpg",
        profession: "Pharmacienne",
        villageOrigine: "Bandjoun",
        lieuResidence: "Douala",
      },
    ],
    famille: [
      {
        categorie: "parents",
        coteFamille: "marie",
        membres: [
          { nom: "M. Kamga Jean", mention: "Pere du marie", villeResidence: "Bafou" },
          { nom: "Mme Kamga nee Teguia Jeanne", mention: "Mere du marie", villeResidence: "Bafou" },
        ],
      },
      {
        categorie: "parents",
        coteFamille: "mariee",
        membres: [
          { nom: "M. Fonkou Pierre", mention: "Pere de la mariee", villeResidence: "Bandjoun" },
          { nom: "Mme Fonkou nee Simo Berthe", mention: "Mere de la mariee", villeResidence: "Bandjoun" },
        ],
      },
      {
        categorie: "freres-soeurs",
        coteFamille: "marie",
        membres: [
          { nom: "Kamga Sandrine", villeResidence: "Yaounde" },
          { nom: "Kamga Patrick", villeResidence: "Paris, France" },
          { nom: "Kamga Noel", villeResidence: "Douala" },
        ],
      },
      {
        categorie: "freres-soeurs",
        coteFamille: "mariee",
        membres: [
          { nom: "Fonkou Carine", villeResidence: "Douala" },
          { nom: "Fonkou Steve", villeResidence: "Montreal, Canada" },
        ],
      },
      {
        categorie: "notable",
        coteFamille: "commun",
        membres: [
          { nom: "Sa Majeste le Chef de Bafou" },
          { nom: "Sa Majeste le Chef de Bandjoun" },
        ],
      },
    ],
    dotItems: [
      { nom: "Vin de raphia", quantite: "5 bidons de 20L", categorie: "boisson", estObligatoire: true },
      { nom: "Vin rouge", quantite: "2 casiers", categorie: "boisson", estObligatoire: true },
      { nom: "Bieres", quantite: "3 casiers", categorie: "boisson", estObligatoire: false },
      { nom: "Huile rouge", quantite: "20 litres", categorie: "nourriture", estObligatoire: true },
      { nom: "Sel", quantite: "2 sacs", categorie: "nourriture", estObligatoire: true },
      { nom: "Chevres", quantite: "2", categorie: "animal", estObligatoire: true },
      { nom: "Poulets", quantite: "4", categorie: "animal", estObligatoire: false },
      { nom: "Pagnes pour la belle-mere", quantite: "3 pagnes wax", categorie: "tissu", estObligatoire: true },
      { nom: "Pagnes pour les tantes", quantite: "6 pagnes", categorie: "tissu", estObligatoire: true },
      { nom: "Noix de cola", quantite: "1 panier", categorie: "nourriture", estObligatoire: true },
      { nom: "Enveloppe pour le pere", categorie: "argent", estObligatoire: true },
      { nom: "Enveloppe pour la mere", categorie: "argent", estObligatoire: true },
      { nom: "Enveloppe pour les oncles maternels", categorie: "argent", estObligatoire: true },
      { nom: "Valise de la mariee", description: "Vetements, chaussures, bijoux, produits de beaute", categorie: "objet", estObligatoire: true },
    ],
    programme: [
      {
        id: "jour-1",
        jour: "Samedi 20 juin 2026",
        evenements: [
          { heure: "07h00", titre: "Accueil des invites et petit-dejeuner", lieu: "Residence Fonkou, Bafoussam", typeEvenement: "reception" },
          { heure: "09h30", titre: "Arrivee de la delegation du marie", lieu: "Residence Fonkou", description: "Presentation officielle de la delegation, discours du porte-parole.", typeEvenement: "traditionnel" },
          { heure: "10h30", titre: "Palabres et negociations de la dot", lieu: "Cour de la residence Fonkou", description: "Le porte-parole du marie presente les elements de la dot. Verification par la famille de la mariee.", typeEvenement: "traditionnel" },
          { heure: "12h00", titre: "Presentation de la mariee", lieu: "Cour de la residence Fonkou", description: "La mariee est presentee officiellement a la delegation du marie.", typeEvenement: "traditionnel", codeVestimentaire: "Tenue traditionnelle" },
          { heure: "12h30", titre: "Benediction des anciens et du chef", lieu: "Cour de la residence Fonkou", description: "Conseils aux maries par les anciens et benediction.", typeEvenement: "traditionnel" },
          { heure: "13h30", titre: "Grand repas de reception", lieu: "Esplanade familiale Fonkou", description: "Menu traditionnel pour 500+ invites.", typeEvenement: "reception" },
          { heure: "15h30", titre: "Animation musicale et danses", lieu: "Esplanade familiale Fonkou", typeEvenement: "reception" },
          { heure: "17h00", titre: "Depart de la mariee", lieu: "Vers la residence Kamga, Bafou", description: "Cortege accompagnant la mariee vers son nouveau foyer.", typeEvenement: "cortege" },
        ],
      },
    ],
    photos: [
      { id: "1", url: "/images/event-1.jpg", caption: "Table d'honneur dressee", type: "photo" as const, tags: ["decoration" as const], addedBy: "ETS Mme Jesus", isDownloadable: true, isCover: false, isRecap: false, order: 1 },
      { id: "2", url: "/images/event-3.jpg", caption: "Vue de la salle", type: "photo" as const, tags: ["reception" as const], addedBy: "ETS Mme Jesus", isDownloadable: true, isCover: false, isRecap: false, order: 2 },
      { id: "3", url: "/images/event-5.jpg", caption: "Details de la decoration", type: "photo" as const, tags: ["decoration" as const], addedBy: "Kamga Sandrine", isDownloadable: true, isCover: false, isRecap: false, order: 3 },
      { id: "4", url: "/images/ceremony-4.jpg", caption: "Preparation des tables", type: "photo" as const, tags: ["reception" as const], addedBy: "Fonkou Carine", isDownloadable: true, isCover: false, isRecap: false, order: 4 },
    ],
    messageInvitation: "C'est avec une immense joie que nous vous invitons a partager ce moment de bonheur avec nos deux familles. Votre presence sera pour nous le plus beau des cadeaux.",
    codeVestimentaire: "Pagne du mariage (tissu wax bleu et or)",
    pagneInfo: "Pagne disponible chez Mme Teguia Jeanne au +237 677 XX XX XX (4 000 FCFA le metre, minimum 6 metres)",
    contactsFamille: [
      { nom: "Kamga Jean (Pere du marie)", telephone: "+237 699 XX XX XX", ville: "Bafou" },
      { nom: "Fonkou Pierre (Pere de la mariee)", telephone: "+237 677 XX XX XX", ville: "Bandjoun" },
      { nom: "Kamga Armel (Le marie)", telephone: "+237 655 XX XX XX", ville: "Douala" },
    ],
    contactOrganisateur: "+1 418 490 1849",
    adresseReception: "Residence Fonkou, quartier Djeleng II, Bafoussam",
    infoHebergement: "Hebergement chez les deux familles. Hotels a proximite : Hotel Talotel Bafoussam (+237 233 44 XX XX)",
    infoTransport: "Navettes depuis Douala : depart Bonaberi 05h00. Contact Patrick Kamga +33 6 XX XX XX XX",
    contributions: {
      message: "Votre presence est notre plus beau cadeau. Toute contribution supplementaire est neanmoins la bienvenue.",
      orangeMoney: "699 XX XX XX (Kamga Jean)",
      mtnMomo: "677 XX XX XX (Fonkou Pierre)",
      nomBeneficiaire: "Comite mariage Kamga-Fonkou",
    },
    isPrivate: false,
    isPublished: true,
    isPending: false,
    allowCondolences: true,
    allowPhotoDownload: true,
    familleName: "Familles Kamga & Fonkou",
    ville: "Bafoussam",
    region: "Ouest",
    coverImage: "/images/event-1.jpg",
    createdAt: "2026-06-01",
    updatedAt: "2026-06-01",
    fairePartDesign: {
      primaryColor: "#2C1810",
      accentColor: "#C9A96E",
      backgroundColor: "#FFF8F0",
      borderStyle: "bamileke",
      template: "mariage",
    },
  },
];

export const demoCondolences: Condolence[] = [
  {
    id: "1",
    fairePartId: "papa-jean-tchinda",
    auteur: "Pierre Kamga",
    lien: "Ancien eleve",
    message: "Monsieur Tchinda etait plus qu'un enseignant pour moi. Il m'a appris la rigueur et l'honnetete. Que son ame repose en paix aupres de nos ancetres.",
    ville: "Douala",
    createdAt: "2026-04-12",
  },
  {
    id: "2",
    fairePartId: "papa-jean-tchinda",
    auteur: "Famille Mboua",
    lien: "Amis de la famille",
    message: "Nous gardons de Papa Jean le souvenir d'un homme bon et genereux. Toutes nos condoleances a la grande famille Tchinda.",
    ville: "Yaounde",
    createdAt: "2026-04-11",
  },
  {
    id: "3",
    fairePartId: "papa-jean-tchinda",
    auteur: "Sarah Tchinda",
    lien: "Petite-fille",
    message: "Grand-pere, tu nous manques deja tellement. Merci pour tout l'amour que tu nous as donne. Tu etais notre boussole. Repose en paix.",
    ville: "Paris, France",
    createdAt: "2026-04-10",
  },
  {
    id: "4",
    fairePartId: "papa-jean-tchinda",
    auteur: "Communaute enseignante de Dschang",
    lien: "Collegue",
    message: "Le corps enseignant perd l'un de ses membres les plus respectes. Son devouement a l'education restera grave dans nos memoires.",
    ville: "Dschang",
    createdAt: "2026-04-09",
  },
  {
    id: "5",
    fairePartId: "mariage-kamga-fonkou",
    auteur: "Tante Berthe",
    lien: "Famille",
    message: "Felicitations a nos enfants ! Que Dieu benisse cette union et vous donne une descendance nombreuse.",
    ville: "Dschang",
    createdAt: "2026-06-15",
  },
];
